#!/bin/bash

gawk '
BEGIN{
	FS = "[ \t\n]+"
}

/^#/{next}

$2=="times" {
	print "# " $0
	++blockid	# start a new block
	doblock[++donest] = blockid
	blocktype[++blocknest] = "times"
	print "do$" blockid "	=	."
	print $1 "	snz"
	print "	jump	@done$" blockid
	print "	neg not"
	next
}

$2=="repeat" {
	print "# " $0
	print $1 "	jump @do$" doblock[donest]
	print "done$" doblock[donest], "	=	."
	if( blocktype[blocknest] == "times" ) print "	drop"
	--donest
	--blocknest
	next
}

{ print $0 }
' $* 
